# ---------- Global definitions -----------
ARG envPath="/opt/inkcut-env"
ARG INKCUT_REPO="https://github.com/inkcut/inkcut.git"

# ---------- Stage 1: Builder ----------
FROM alpine:3 AS builder
ARG envPath
ARG INKCUT_REPO

# Install runtime + build dependencies
RUN apk add --no-cache \
    python3 \
    py3-lxml \
    py3-pip \
    py3-pycups \
    py3-packaging \
    py3-qt6 \
    qt6-qtbase-dev \
    qt6-qtwayland-dev \
    build-base \
    cups-dev \
    git

# Create & activate python virtual environment (where inkcut will be installed)
RUN python3 -m venv --system-site-packages $envPath
ENV PATH="$envPath/bin:$PATH"

# Clone the github repository & build/install there-from
WORKDIR /src
RUN INKCUT_REF=$(git ls-remote --tags --sort="v:refname" $INKCUT_REPO | tail -n1 | sed 's/.*\///; s/\^{}//') && \
git clone --depth 1 --branch ${INKCUT_REF} ${INKCUT_REPO} inkcut-source
RUN pip install --no-cache-dir ./inkcut-source

# Generate the .desktop file
RUN mkdir -p $envPath/share/applications
RUN cat > $envPath/share/applications/inkcut.desktop <<EOL
[Desktop Entry]
Name=Inkcut
GenericName=Terminal entering Inkcut
Comment=Terminal entering Inkcut
Categories=Distrobox;System;Utility
Exec=inkcut
Icon=$envPath/share/icons/inkcut.svg
Keywords=distrobox;
NoDisplay=false
Terminal=false
Type=Application
EOL

RUN mkdir -p $envPath/share/icons
RUN cp $envPath/lib/python*/site-packages/inkcut/res/media/inkcut.svg $envPath/share/icons/inkcut.svg || true

# ---------- Stage 2: Runtime ----------
FROM alpine:3
ARG envPath

# Install runtime dependencies
RUN apk add --no-cache \
    python3 \
    py3-lxml \
    py3-pycups \
    py3-packaging \
    py3-qt6 \
    cups-libs \
    qt6-qtbase \
    qt6-qtsvg \
    qt6-qtdeclarative \
    qt6-qtserialport \
    qt6-qtwayland

# Copy (& reference) the virtual environment from the builder stage
COPY --from=builder $envPath $envPath
ENV PATH="$envPath/bin:$PATH"

# Set the entrypoint
CMD ["inkcut"]
